# Generated by Django 5.1.4 on 2024-12-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_class', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_class', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('lesson_plan', models.FileField(upload_to='lesson_plans/')),
                ('lesson_note', models.FileField(upload_to='lesson_notes/')),
                ('assessment_question', models.FileField(upload_to='assessments')),
                ('exam_question', models.FileField(upload_to='examination')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(max_length=11)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('date_of_employment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('form_class', models.CharField(choices=[('JS1', 'JS1'), ('JS2', 'JS2'), ('JS3', 'JS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], max_length=10)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('year_admitted', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
